# Generated by Django 2.1.4 on 2018-12-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181212_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='author',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='viewuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='viewuser',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
