# Generated by Django 2.1.4 on 2018-12-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181216_0009'),
        ('main', '0003_auto_20181215_2116'),
    ]

    operations = [
    ]
