# Generated by Django 2.1.4 on 2018-12-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181216_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='issuedate',
            field=models.DateField(),
        ),
    ]
