# Generated by Django 2.1.4 on 2018-12-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181218_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
